#!/usr/bin/env python3
"""ROS executable wrapper for the backend-switchable open detector."""

from autoware_ml_model_launchers.open_detector.ros_node import main


if __name__ == "__main__":
    main()
