#!/usr/bin/env python3
"""ROS executable wrapper for the screen capture pseudo camera node."""

from autoware_ml_model_launchers.screen_camera.ros_node import main


if __name__ == "__main__":
    main()
